//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityMS_CRUD_ASP.NET_MVC.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int student_id { get; set; }
        public string Student_name { get; set; }
        public int student_cgpa { get; set; }
    }
}
